import { Analytics } from '@vercel/analytics/react';
import { AppWrapper } from './(context)/AppWrapper'
import { ChakraUIProviders } from './chakraUI/ChakraUIProviders'
import { openSauceOne } from './chakraUI/ChakraUIFont'
import './globals.css'

export const metadata = {
  title: 'Sri Jaya PS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSauceOne.OpenSauceOne.className}`}>
        <AppWrapper>
          <ChakraUIProviders>
            {children}
            <Analytics />
          </ChakraUIProviders>
        </AppWrapper>
      </body>
    </html>
  )
}
